const $=s=>document.querySelector(s), app=$('#app');
const D={settings:{appName:'Portal TBSA',logoSubtitle:'Gestão inteligente de requisições',homeTitle:'Bem-vinda ao Portal TBSA',homeSubtitle:'Acompanhamento semanal de diesel, materiais, insumos e bits',description:'Centralize seus dashboards do Power BI em um só lugar.',footerText:'Controle interno TBSA para acompanhamento de requisições e custos.',primary:'#0b5fc6',secondary:'#0d756e',accent:'#f6b8ce',background:'#f2f7fd',font:'Segoe UI',radius:14,logo:'',theme:'claro'},pages:[{id:'geral',name:'Visão Geral',title:'Dashboard Geral',subtitle:'Acompanhamento dos pedidos e custos da operação',url:''},{id:'diesel',name:'Diesel',title:'Dashboard de Diesel',subtitle:'Pedidos, litros e custos semanais',url:''},{id:'perfuracao',name:'Materiais de Perfuração',title:'Materiais de Perfuração',subtitle:'Itens, quantidades e valores',url:''},{id:'insumos',name:'Insumos',title:'Dashboard de Insumos',subtitle:'Solicitações e custos',url:''},{id:'bits',name:'Bits',title:'Dashboard de Bits',subtitle:'Consumo e custo de bits',url:''}],users:[]};
let records=JSON.parse(localStorage.getItem('tbsa-records')||'[]'), charts=[];
let db=JSON.parse(localStorage.getItem('tbsa-db')||'null')||structuredClone(D), session=JSON.parse(sessionStorage.getItem('tbsa-session')||'null'), view='geral', tab='aparencia';
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function init(){if(!db.users.length){db.users=[{id:crypto.randomUUID(),name:'Michele Buril',email:'michele@empresa.com',role:'Administradora',active:true,password:await hash('123456')}];save()}apply(); render()}
function save(){localStorage.setItem('tbsa-db',JSON.stringify(db))} function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function apply(){let s=db.settings;document.documentElement.style.cssText=`--primary:${s.primary};--secondary:${s.secondary};--accent:${s.accent};--bg:${s.background};--font:${s.font},Arial,sans-serif;--radius:${s.radius}px`;document.title=s.appName}
function toast(t){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(t)}</div>`);setTimeout(()=>$('.toast')?.remove(),2200)}
function logo(){let s=db.settings;return `<div class="logo">${s.logo?`<img src="${s.logo}">`:esc(s.appName[0]||'T')}</div>`}
function render(){session?renderApp():renderLogin()}
function renderLogin(){let s=db.settings;app.innerHTML=`<section class="login"><div class="login-hero"><div class="logo-row">${logo()}<span>${esc(s.appName)}</span></div><div class="hero-copy"><h1>${esc(s.homeTitle)}</h1><p>${esc(s.homeSubtitle)}</p></div><div class="hero-bottom">${esc(s.footerText)}</div></div><div class="login-box"><h2>Entrar</h2><p class="muted">Use seu e-mail e senha para acessar o sistema.</p><form id="loginForm"><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>Senha</label><input name="password" type="password" required></div><div id="err" class="error"></div><button class="btn btn-primary btn-block">Entrar</button></form><div class="hint"><strong>Primeiro acesso</strong><p class="small">E-mail: michele@empresa.com<br>Senha: 123456</p><p class="small">Altere a senha em Configurações após entrar.</p></div></div></section>`;$('#loginForm').onsubmit=login}
async function login(e){e.preventDefault();let f=new FormData(e.target),u=db.users.find(x=>x.email.toLowerCase()===String(f.get('email')).toLowerCase()&&x.active);if(!u||u.password!==await hash(f.get('password'))){$('#err').textContent='E-mail ou senha incorretos.';return}session={id:u.id};sessionStorage.setItem('tbsa-session',JSON.stringify(session));render()}
function current(){return db.users.find(x=>x.id===session?.id)}
function renderApp(){let u=current();if(!u){logout();return}let s=db.settings;app.innerHTML=`<div class="shell"><aside class="sidebar" id="side"><div class="logo-row">${logo()}<div><div class="brand-title">${esc(s.appName)}</div><div class="brand-sub">${esc(s.logoSubtitle)}</div></div></div><nav class="nav"><button data-v="inicio">Início</button><button data-v="importar">Importar dados</button>${db.pages.map(p=>`<button data-v="${p.id}">${esc(p.name)}</button>`).join('')}<button data-v="usuarios">Usuários</button><button data-v="config">Configurações</button><button data-v="sobre">Sobre</button></nav><div class="userfoot"><strong>${esc(u.name)}</strong><span>${esc(u.role)}</span><button class="linkbtn" id="logout">Sair</button></div></aside><main class="main"><div id="content"></div></main></div>`;document.querySelectorAll('[data-v]').forEach(x=>x.onclick=()=>{view=x.dataset.v;draw()});$('#logout').onclick=logout;draw()}
function logout(){session=null;sessionStorage.removeItem('tbsa-session');render()}
function head(t,sub){let u=current();return `<header class="top"><button class="btn btn-outline mobile" onclick="document.querySelector('#side').classList.toggle('open')">☰</button><div><h1>${esc(t)}</h1><p>${esc(sub||'')}</p></div><div class="top-actions"><div class="avatar">${u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div></div></header>`}
function draw(){document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x.dataset.v===view));if(view==='config')settings();else if(view==='usuarios')users();else if(view==='importar')importData();else if(view==='inicio')home();else if(view==='sobre')about();else dashboard(db.pages.find(p=>p.id===view)||db.pages[0])}
function home(){let s=db.settings;$('#content').innerHTML=head(s.homeTitle,s.homeSubtitle)+`<div class="grid four">${db.pages.slice(1).map(p=>`<button class="card" style="text-align:left;cursor:pointer" onclick="view='${p.id}';draw()"><h2>${esc(p.name)}</h2><p class="muted">${esc(p.subtitle)}</p></button>`).join('')}</div><section class="card"><h2>${esc(s.description)}</h2><p class="muted">Use o menu lateral para abrir cada painel ou ajustar o portal em Configurações.</p></section>`}
function dashboard(p){
  const category=p.id==='geral'?'':norm(p.name), rows=category?records.filter(r=>norm(r.categoria).includes(category.split(' ')[0])):records;
  const weeks=[...new Set(rows.map(r=>r.semana).filter(Boolean))];
  const total=rows.reduce((a,r)=>a+num(r.valor),0), qty=rows.reduce((a,r)=>a+num(r.quantidade||1),0);
  $('#content').innerHTML=head(p.title,p.subtitle)+`<div class="grid four"><section class="card"><span class="muted">Registros</span><h2>${rows.length}</h2></section><section class="card"><span class="muted">Valor total</span><h2>${money(total)}</h2></section><section class="card"><span class="muted">Quantidade</span><h2>${fmt(qty)}</h2></section><section class="card"><span class="muted">Semanas</span><h2>${weeks.length}</h2></section></div>${rows.length?`<div class="grid two"><section class="card"><h2>Valor por semana</h2><canvas id="weekChart"></canvas></section><section class="card"><h2>Distribuição por categoria</h2><canvas id="catChart"></canvas></section></div><section class="card"><h2>Itens com maior valor</h2><canvas id="itemChart"></canvas></section><section class="card"><h2>Registros</h2>${dataTable(rows)}</section>`:`<section class="card empty"><div><h2>Nenhum dado importado</h2><p>Abra Importar dados, selecione sua planilha e faça o mapeamento das colunas.</p><button class="btn btn-primary" onclick="view='importar';draw()">Importar planilha</button></div></section>`}`;
  if(rows.length) renderCharts(rows);
}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function num(v){if(typeof v==='number')return v;let x=String(v??'').replace(/\s/g,'').replace(/R\$/gi,'');if(x.includes(',')&&x.includes('.'))x=x.replace(/\./g,'').replace(',','.');else x=x.replace(',','.');return Number(x)||0}
function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)}
function fmt(v){return new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v)}
function group(rows,key,val='valor'){let o={};rows.forEach(r=>{let k=r[key]||'Não informado';o[k]=(o[k]||0)+num(r[val])});return o}
function renderCharts(rows){charts.forEach(c=>c.destroy());charts=[];let w=group(rows,'semana'),c=group(rows,'categoria'),i=group(rows,'item');let top=Object.entries(i).sort((a,b)=>b[1]-a[1]).slice(0,10);let color=getComputedStyle(document.documentElement).getPropertyValue('--primary').trim();Chart.defaults.font.family=getComputedStyle(document.body).fontFamily;charts.push(new Chart($('#weekChart'),{type:'bar',data:{labels:Object.keys(w),datasets:[{label:'Valor',data:Object.values(w),backgroundColor:color}]},options:{responsive:true}}));charts.push(new Chart($('#catChart'),{type:'doughnut',data:{labels:Object.keys(c),datasets:[{data:Object.values(c)}]},options:{responsive:true}}));charts.push(new Chart($('#itemChart'),{type:'bar',data:{labels:top.map(x=>x[0]),datasets:[{label:'Valor',data:top.map(x=>x[1]),backgroundColor:color}]},options:{indexAxis:'y',responsive:true}}))}
function dataTable(rows){return `<div style="overflow:auto"><table class="table"><thead><tr><th>Semana</th><th>Categoria</th><th>Item</th><th>Requisição</th><th>Quantidade</th><th>Valor</th></tr></thead><tbody>${rows.slice(0,200).map(r=>`<tr><td>${esc(r.semana)}</td><td>${esc(r.categoria)}</td><td>${esc(r.item)}</td><td>${esc(r.requisicao)}</td><td>${fmt(num(r.quantidade))}</td><td>${money(num(r.valor))}</td></tr>`).join('')}</tbody></table></div>`}
let pendingRows=[], pendingHeaders=[];
function importData(){
 $('#content').innerHTML=head('Importar dados','Carregue sua planilha Excel ou CSV e atualize o dashboard')+`<section class="card"><h2>1. Escolha o arquivo</h2><p class="muted">A primeira linha deve conter os nomes das colunas.</p><div class="field"><input id="dataFile" type="file" accept=".xlsx,.xls,.csv"></div><div id="mapArea"></div></section><section class="card"><h2>Dados atuais</h2><p>${records.length} registros armazenados neste navegador.</p><div class="actions" style="justify-content:flex-start"><button id="exportCsv" class="btn btn-outline">Exportar CSV</button><button id="clearData" class="btn btn-danger">Apagar dados</button></div></section>`;
 $('#dataFile').onchange=readWorkbook;$('#clearData').onclick=()=>{if(confirm('Apagar todos os dados importados?')){records=[];localStorage.removeItem('tbsa-records');importData()}};$('#exportCsv').onclick=exportCSV;
}
function readWorkbook(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=ev=>{let wb=XLSX.read(ev.target.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];pendingRows=XLSX.utils.sheet_to_json(ws,{defval:''});pendingHeaders=Object.keys(pendingRows[0]||{});showMapping(f.name)};r.readAsArrayBuffer(f)}
function guess(keys){let aliases={semana:['semana','week'],categoria:['categoria','tipo','grupo'],item:['item','material','descricao','produto','insumo'],requisicao:['requisicao','req','pedido'],quantidade:['quantidade','qtd','litros','volume'],valor:['valor total','valor','custo','preco total'],data:['data','date']};let out={};for(let k in aliases)out[k]=pendingHeaders.find(h=>aliases[k].some(a=>norm(h).includes(a)))||'';return out}
function showMapping(name){let g=guess(), fields=[['semana','Semana'],['categoria','Categoria'],['item','Item/Material'],['requisicao','Requisição/Pedido'],['quantidade','Quantidade/Litros'],['valor','Valor/Custo'],['data','Data']];$('#mapArea').innerHTML=`<h2 class="section-title">2. Relacione as colunas</h2><p class="muted">Arquivo: ${esc(name)} • ${pendingRows.length} linhas encontradas</p><form id="mapForm"><div class="grid two">${fields.map(([k,l])=>`<div class="field"><label>${l}</label><select name="${k}"><option value="">Não usar</option>${pendingHeaders.map(h=>`<option ${g[k]===h?'selected':''}>${esc(h)}</option>`).join('')}</select></div>`).join('')}</div><div class="field"><label>Modo de importação</label><select name="mode"><option value="replace">Substituir dados atuais</option><option value="append">Adicionar aos dados atuais</option></select></div><div class="actions"><button class="btn btn-primary">Importar e criar dashboard</button></div></form>`;$('#mapForm').onsubmit=finishImport}
function finishImport(e){e.preventDefault();let m=Object.fromEntries(new FormData(e.target)),converted=pendingRows.map(row=>({semana:m.semana?row[m.semana]:'',categoria:m.categoria?row[m.categoria]:'',item:m.item?row[m.item]:'',requisicao:m.requisicao?row[m.requisicao]:'',quantidade:m.quantidade?row[m.quantidade]:'',valor:m.valor?row[m.valor]:'',data:m.data?row[m.data]:''}));records=m.mode==='append'?[...records,...converted]:converted;localStorage.setItem('tbsa-records',JSON.stringify(records));toast('Dashboard atualizado');view='geral';draw()}
function exportCSV(){if(!records.length)return toast('Não há dados para exportar');let ws=XLSX.utils.json_to_sheet(records),csv=XLSX.utils.sheet_to_csv(ws),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='dados-dashboard-tbsa.csv';a.click()}
function about(){let s=db.settings;$('#content').innerHTML=head('Sobre',s.appName)+`<section class="card"><h2>${esc(s.appName)}</h2><p>${esc(s.description)}</p><p class="muted">${esc(s.footerText)}</p></section>`}
function tabs(){let a=[['aparencia','Aparência e textos'],['tema','Cores e tema'],['abas','Abas'],['acessos','Acessos'],['dados','Backup']];return `<div class="card tabs">${a.map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>`}
function settings(){let s=db.settings;$('#content').innerHTML=head('Configurações','Personalize as informações, acessos e aparência do portal')+tabs()+`<div id="settingBody"></div>`;document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;settings()});let b=$('#settingBody');if(tab==='aparencia')b.innerHTML=`<form id="setForm" class="card"><h2>Informações do portal</h2><p class="muted">Edite os textos que aparecem no sistema.</p><div class="grid two">${inp('appName','Nome do app',s.appName)}${inp('logoSubtitle','Subtítulo perto da logo',s.logoSubtitle)}${inp('homeTitle','Título da tela inicial',s.homeTitle)}${inp('homeSubtitle','Subtítulo da tela inicial',s.homeSubtitle)}${area('description','Descrição do portal',s.description)}${area('footerText','Texto inferior da tela de entrada',s.footerText)}</div><h3 class="section-title">Logo</h3><div class="field"><label>Enviar imagem</label><input id="logoFile" type="file" accept="image/*"><span class="small muted">A imagem fica salva neste navegador.</span></div><div class="actions"><button class="btn btn-primary">Salvar alterações</button></div></form>`;else if(tab==='tema')b.innerHTML=`<form id="setForm" class="card"><h2>Cores, fonte e formato</h2><div class="grid four">${color('primary','Cor principal',s.primary)}${color('secondary','Cor secundária',s.secondary)}${color('accent','Cor de destaque',s.accent)}${color('background','Fundo',s.background)}${selectFont(s.font)}${inp('radius','Arredondamento',s.radius,'number')}</div><div class="actions"><button class="btn btn-outline" type="button" id="resetTheme">Restaurar padrão</button><button class="btn btn-primary">Aplicar tema</button></div></form>`;else if(tab==='abas')b.innerHTML=`<form id="pagesForm" class="card"><h2>Abas e dashboards</h2><p class="muted">Altere nomes, títulos, descrições e links do Power BI.</p>${db.pages.map((p,i)=>`<div class="card"><div class="grid two">${inp(`name${i}`,'Nome no menu',p.name)}${inp(`title${i}`,'Título da tela',p.title)}${inp(`subtitle${i}`,'Subtítulo',p.subtitle)}${inp(`url${i}`,'Link seguro do Power BI',p.url)}</div></div>`).join('')}<div class="actions"><button class="btn btn-primary">Salvar abas</button></div></form>`;else if(tab==='acessos')b.innerHTML=accessForm(current());else b.innerHTML=backup();bindSettings()}
function inp(n,l,v,t='text'){return `<div class="field"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}"></div>`}function area(n,l,v){return `<div class="field"><label>${l}</label><textarea name="${n}">${esc(v)}</textarea></div>`}function color(n,l,v){return `<div class="field"><label>${l}</label><input name="${n}" type="color" value="${v}"></div>`}function selectFont(v){let a=['Segoe UI','Arial','Verdana','Georgia','Trebuchet MS'];return `<div class="field"><label>Fonte</label><select name="font">${a.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`}
function accessForm(u){return `<form id="accessForm" class="card"><h2>Meu cadastro</h2><p class="muted">Atualize seus dados e sua senha de acesso.</p><div class="grid two">${inp('name','Nome',u.name)}${inp('email','E-mail',u.email,'email')}${inp('role','Função',u.role)}${inp('password','Nova senha','','password')}</div><div class="actions"><button class="btn btn-primary">Salvar cadastro</button></div></form>`}
function backup(){return `<section class="card"><h2>Backup das configurações</h2><p class="muted">Exporte antes de trocar de computador ou navegador.</p><div class="actions" style="justify-content:flex-start"><button class="btn btn-primary" id="export">Exportar arquivo</button><label class="btn btn-outline">Importar arquivo<input id="import" class="hidden" type="file" accept="application/json"></label><button class="btn btn-danger" id="reset">Restaurar portal</button></div></section>`}
function bindSettings(){let f=$('#setForm');if(f)f.onsubmit=e=>{e.preventDefault();Object.assign(db.settings,Object.fromEntries(new FormData(f)));db.settings.radius=Number(db.settings.radius)||14;save();apply();toast('Alterações salvas');settings()};let lf=$('#logoFile');if(lf)lf.onchange=e=>{let r=new FileReader();r.onload=()=>{db.settings.logo=r.result;save();apply();settings()};r.readAsDataURL(e.target.files[0])};let rt=$('#resetTheme');if(rt)rt.onclick=()=>{Object.assign(db.settings,{primary:D.settings.primary,secondary:D.settings.secondary,accent:D.settings.accent,background:D.settings.background,font:D.settings.font,radius:14});save();apply();settings()};let pf=$('#pagesForm');if(pf)pf.onsubmit=e=>{e.preventDefault();let f=new FormData(pf);db.pages.forEach((p,i)=>['name','title','subtitle','url'].forEach(k=>p[k]=f.get(k+i)));save();toast('Abas atualizadas')};let af=$('#accessForm');if(af)af.onsubmit=async e=>{e.preventDefault();let f=new FormData(af),u=current();u.name=f.get('name');u.email=f.get('email');u.role=f.get('role');if(f.get('password'))u.password=await hash(f.get('password'));save();toast('Cadastro atualizado');renderApp();view='config';tab='acessos';settings()};let ex=$('#export');if(ex)ex.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='portal-tbsa-backup.json';a.click()};let im=$('#import');if(im)im.onchange=e=>{let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();apply();toast('Backup importado');renderApp()}catch{toast('Arquivo inválido')}};r.readAsText(e.target.files[0])};let rs=$('#reset');if(rs)rs.onclick=()=>{if(confirm('Restaurar todas as configurações?')){localStorage.removeItem('tbsa-db');location.reload()}}}
function users(){let me=current();$('#content').innerHTML=head('Usuários','Cadastre acessos e defina permissões')+`<section class="card"><div class="warning"><strong>Importante:</strong> no GitHub Pages estes acessos ficam salvos somente neste navegador. Para acesso seguro por várias pessoas é necessário conectar uma autenticação com servidor.</div><h2 class="section-title">Novo usuário</h2><form id="userForm"><div class="grid four">${inp('name','Nome','')}${inp('email','E-mail','','email')}${inp('role','Função','Usuário')}${inp('password','Senha inicial','','password')}</div><div class="actions"><button class="btn btn-primary">Cadastrar</button></div></form></section><section class="card"><h2>Usuários cadastrados</h2><table class="table"><thead><tr><th>Nome</th><th>E-mail</th><th>Função</th><th>Status</th><th></th></tr></thead><tbody>${db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td><span class="badge">${u.active?'Ativo':'Bloqueado'}</span></td><td>${u.id!==me.id?`<button class="linkbtn toggle" data-id="${u.id}">${u.active?'Bloquear':'Ativar'}</button>`:''}</td></tr>`).join('')}</tbody></table></section>`;$('#userForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);if(db.users.some(u=>u.email.toLowerCase()===f.get('email').toLowerCase())){toast('E-mail já cadastrado');return}db.users.push({id:crypto.randomUUID(),name:f.get('name'),email:f.get('email'),role:f.get('role'),active:true,password:await hash(f.get('password'))});save();users();toast('Usuário cadastrado')};document.querySelectorAll('.toggle').forEach(x=>x.onclick=()=>{let u=db.users.find(u=>u.id===x.dataset.id);u.active=!u.active;save();users()})}
init();